create table if not exists public.place_applications (
  id bigint generated by default as identity primary key,
  local_id text,
  type text not null default 'create',
  status text not null default 'pending',
  place_id bigint,
  payload jsonb not null,
  submitted_by_name text,
  submitted_by_phone text,
  submitted_by_email text,
  owner_note text,
  review_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists place_applications_status_idx on public.place_applications (status);
create index if not exists place_applications_phone_idx on public.place_applications (submitted_by_phone);
create index if not exists place_applications_submitted_idx on public.place_applications (submitted_at desc);

create or replace function public.touch_place_applications_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_place_applications_updated_at on public.place_applications;
create trigger trg_place_applications_updated_at
before update on public.place_applications
for each row execute procedure public.touch_place_applications_updated_at();

alter table public.place_applications enable row level security;

drop policy if exists place_applications_read_all on public.place_applications;
create policy place_applications_read_all
on public.place_applications
for select
to anon, authenticated
using (true);

drop policy if exists place_applications_insert_all on public.place_applications;
create policy place_applications_insert_all
on public.place_applications
for insert
to anon, authenticated
with check (true);

drop policy if exists place_applications_update_all on public.place_applications;
create policy place_applications_update_all
on public.place_applications
for update
to anon, authenticated
using (true)
with check (true);
